http:
  port: 9000
  healthcheck: /health
  ws: /ws
  timeout: 300
  route_maps:
    - name: open-aku-staff
      host: aku-staff:80
      override_path: /api/aku-staff/internal
      upstream_path: /internal
      plugins:
        - circuit-breaker
        - ip-restriction
        - cors
        - disable
      cors:
        origins:
        methods:
        headers:
        credentials: false
        preflight_continue: false
      ip_restriction:
    - name: open-aku-user
      host: aku-user:80
      override_path: /api/aku-user/internal
      upstream_path: /internal
      plugins:
        - rate-limiting

grpc:
  port: 10000
  keep_connection: false
  timeout: 300
  method_maps:
    - name: open-grpc-aku-staff
      host: aku-staff:10000
      proto_service: pb.AkuStaff
      allow:
        - IamPolicy
      disallow:
      plugins:
        - circuit-breaker
    - name: open-grpc-aku-user
      host: aku-user:10000
      proto_service: pb.AkuUser
      allow:
      disallow:
        - nothing
      plugins:
        - circuit-breaker

ip_forwarded_header: X-Forwarded-For